### ISSUE TITLE
[Feedback]: Slack

### ISSUE THREAD

**Issue by wfigueroa-chwy** [chromaui/chromatic-docs#502]
### Describe the problem

Slack's requirements for profile pictures state that they should be at a minimum 512x512. The [provided custom icon](https://www.chromatic.com/docs/_astro/chromatic-slack-icon.D5p6IHJp_AsoAd.webp) to use for Slack is only 100x100 which fails to work.

The icon should be replaced with a larger size to meet the requirements, ideally 1024x1024.

### URL of the page with the issue

https://chromatic.com/docs/slack

### Additional context

See here for requirements https://slack.com/help/articles/115005506003-Upload-a-profile-photo

**Comment by winkerVSbecks** [comment]
Thanks for reporting. The fix is up.
