### ISSUE TITLE
[Feedback]: Visual Tests addon for Storybook - OS-sensitive rendering 

### ISSUE THREAD

**Issue by yairEO** [chromaui/chromatic-docs#543]
### Describe the problem

I was going over the page and FAQ and did not find information regarding visual testing in a team where developers use different machines (OS/browsers) a things might render a bit differently.

Such an important thing should be addressed

### URL of the page with the issue

https://chromatic.com/docs/visual-tests-addon

**Comment by winkerVSbecks** [comment]
Not sure I understand why that matters. Tests run in the cloud, not on your local machine.
